services:
  - type: web
    name: sharevia-signal
    env: node
    plan: free
    rootDir: signal-server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 10000
      - key: PEER_PATH
        value: /peerjs
      - key: CORS_ORIGIN
        value: "*" # Set this to your Netlify URL later
